name: Container Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t discord-bot:test .

    - name: Install Container Structure Test
      run: |
        wget https://github.com/GoogleContainerTools/container-structure-test/releases/download/v1.15.0/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

    - name: Run Container Structure Tests
      run: |
        container-structure-test test --image discord-bot:test --config tests/container/container-structure-tests.yaml

    # - name: Push Docker Image to Registry (Disabled until registry is set up)
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     echo "Pushing image to registry..."
    #     docker tag discord-bot:test registry/discord-bot:latest
    #     docker push registry/discord-bot:latest
