name: Container Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract Short Commit SHA
      id: get_sha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        load: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}
        labels: |
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
        cache-from: |
          type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
        cache-to: |
          type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max

    - name: Install Container Structure Test
      run: |
        wget https://github.com/GoogleContainerTools/container-structure-test/releases/download/v1.15.0/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

    - name: Run Container Structure Tests
      run: |
        container-structure-test test --image ghcr.io/${{ github.repository }}:latest --config tests/container/container-structure-tests.yaml

    - name: Push Docker Image
      uses: docker/build-push-action@v5
      if: github.ref == 'refs/heads/main' && success()
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ env.SHORT_SHA }}
        cache-from: |
          type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max
        cache-to: |
          type=registry,ref=ghcr.io/${{ github.repository }}:cache,mode=max